"""Add user_type field to users table

Revision ID: 0c681de6b16a
Revises: ad600ceb684b
Create Date: 2025-10-24 13:00:43.560605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c681de6b16a'
down_revision = 'ad600ceb684b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite는 ALTER COLUMN을 지원하지 않으므로 user_type 컬럼만 추가
    op.add_column('users', sa.Column('user_type', sa.String(10), server_default='real', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###