"""Add persona fields to users table

Revision ID: 4a221540802d
Revises: 0c681de6b16a
Create Date: 2025-10-24 14:26:08.735019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a221540802d'
down_revision = '0c681de6b16a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite는 ALTER COLUMN을 지원하지 않으므로 컬럼 추가만 진행
    op.add_column('users', sa.Column('ethnicity', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('persona_age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('persona_gender', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('persona_occupation', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('persona_interests', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('persona_activity_level', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('persona_posting_style', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('persona_korean_level', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('persona_russian_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'persona_russian_level')
    op.drop_column('users', 'persona_korean_level')
    op.drop_column('users', 'persona_posting_style')
    op.drop_column('users', 'persona_activity_level')
    op.drop_column('users', 'persona_interests')
    op.drop_column('users', 'persona_occupation')
    op.drop_column('users', 'persona_gender')
    op.drop_column('users', 'persona_age')
    op.drop_column('users', 'ethnicity')
    # ### end Alembic commands ###