"""Add is_group field to categories

Revision ID: 8709aa2249be
Revises: ab64a494f26d
Create Date: 2025-10-23 00:46:41.827528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8709aa2249be'
down_revision = 'ab64a494f26d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_group', sa.Boolean(), nullable=True))
    # SQLite doesn't support ALTER COLUMN, so we skip the users table modification
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_group')
    # ### end Alembic commands ###