"""Add nickname_ko and nickname_ru fields

Revision ID: 9f6d420a68f6
Revises: 4a221540802d
Create Date: 2025-10-24 14:57:46.760385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6d420a68f6'
down_revision = '4a221540802d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite는 ALTER COLUMN을 지원하지 않으므로 컬럼 추가만 진행
    op.add_column('users', sa.Column('nickname_ko', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('nickname_ru', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname_ru')
    op.drop_column('users', 'nickname_ko')
    # ### end Alembic commands ###