"""Add layout_type and permission to categories

Revision ID: ab64a494f26d
Revises: 0d46cf638c32
Create Date: 2025-10-22 23:28:44.693319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab64a494f26d'
down_revision = '0d46cf638c32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('layout_type', sa.Enum('LIST', 'GALLERY', 'CARD', 'GRID', name='categorylayouttype'), nullable=True))
    op.add_column('categories', sa.Column('permission', sa.Enum('PUBLIC', 'READ_ALL', 'LOGIN_ONLY', 'ADMIN_ONLY', name='categorypermission'), nullable=True))

    # SQLite doesn't support ALTER COLUMN, so we skip the users table modification
    # The oauth_provider field will work fine with VARCHAR type
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'permission')
    op.drop_column('categories', 'layout_type')
    # ### end Alembic commands ###